Repository daedalus-developers/daedalus.codes, pull requests merged in 2023-09, with the labels that each got.

#19 #6 Footer
  .github/workflows/ci.yaml
  .github/workflows/playwright.yaml
  .github/workflows/vitest.yaml
  .gitignore
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app.html
  src/index.test.ts
  src/lib/components/Footer.svelte
  src/lib/components/Header.svelte
  src/lib/components/Hero.svelte
  src/lib/components/Megaphone.svelte
  src/lib/components/Mission.svelte
  src/lib/components/icons/CloseIcon.svelte
  src/lib/components/icons/GitHub.svelte
  src/lib/components/icons/HamburgerIcon.svelte
  src/lib/components/icons/Icon.svelte
  src/lib/components/icons/Moon.svelte
  src/lib/components/icons/Sun.svelte
  src/lib/components/sections/BlogSection.svelte
  src/lib/data/links.ts
  src/lib/helper.ts
  src/routes/(landing)/+layout.svelte
  src/routes/(landing)/+page.svelte
  src/routes/(landing)/Footer.svelte
  src/routes/(landing)/Header.svelte
  src/routes/(landing)/Header.test.ts
  src/routes/(landing)/members/+page.svelte
  src/routes/(landing)/members/+page.ts
  src/test.config.ts
  static/hero.png
  tailwind.config.ts
  test.config.ts
  tests/landing.test.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#27 Create two stack choice component
  src/lib/components/coursePath/StackChoice.svelte
  src/lib/data/index.ts
Labels: feature

#50 Denvie/33 courseproject section component
  src/lib/components/coursePath/CourseContent.svelte
  src/lib/components/coursePath/LeftSideNavbar.svelte
Labels: feature

#54 Denvie/37-course-selection-page
  src/lib/components/coursePath/CourseContent.svelte
  src/lib/components/coursePath/LeftSideNavbar.svelte
  src/lib/components/coursePath/StackChoice.svelte
  src/routes/(landing)/courses/+page.svelte
  src/routes/(landing)/courses/[courseStack]/+page.svelte
Labels: enhancement, feature

#68 #47 #48 Fix all navbar - related issues
  src/lib/components/utils/ToggleTheme.svelte
  src/routes/(landing)/Header.svelte
Labels: bug

#70 Fix mobile navbar #69
  src/routes/(landing)/Header.svelte
Labels: bug
